### ISSUE TITLE
003-ADR-Communication-&-Interfaces

### ISSUE THREAD

**Issue by HeitorMP** [SEAME-pt/T07-DES_Instrument-Cluster#22]
---
# Configuration of the communication system between all components of the vehicle in SEA:ME context, to control the Racer "Waveshare" 
parent: Decisions
nav_order: 003
title: Communications System Architecture Decision Record

## decision-makers: 
   - Nuno Taboada
   - Heitor Maciel
   - Ivo Marques
   - Antonio Ferreira

## consulted: 
  - Felipe Prezado (fp@seame.pt)
  - Pedro Batista (pb@seame.pt)
  - Paulo Silva (ps@seame.pt)
## informed: 
  - Felipe Prezado (fp@seame.pt)
  - Pedro Batista (pb@seame.pt)
  - Paulo Silva (ps@seame.pt)
---

# Which Communications Protocls

## Context and Problem Statement

The ADR 001 (#23 ) considered a multiple platform hardware architecture. This ADR together with the Course Book subject requires multiple communications protocols.
Some protocols are bare naked requirement as for the CAM and for the TFTLCD, others are required by the subject and lastly required by the above mentioned ADR 001.

## Decision Drivers

* the features and settings challenges of multiple hardware platforms
* integration of different types of control hardware, from CPU, GPU and MicroController universe of hardware sensors and displays
* implementation of performant solutions when implementing in AI and ML

### Comparison Table

| Protocol | Bandwidth      | Distance       | Latency | Robustness | Security | Cost  | Use Cases                                   |
|----------|----------------|----------------|---------|------------|----------|-------|--------------------------------------------|
| TCP/IP   | High           | Long (Global)  | High    | Moderate   | High     | High  | Cloud integration, diagnostics             |
| CAN      | Low (1 Mbps)   | Medium (~40m)  | Low     | High       | Low      | Low   | Intra-vehicle communication, safety        |
| I²C      | Low (400 kbps) | Short (~1m)    | Low     | Moderate   | Low      | Low   | Sensors, low-speed peripherals             |
| SPI      | High (10+ Mbps)| Short (~10m)   | Low     | Moderate   | Low      | Low   | High-speed sensors, displays, ADCs         |

---

## Decision Outcome
1. **Intra-Vehicle ECU Communication**: Use **CAN** for its real-time capabilities and reliability.
2. **ECU-to-Peripheral Communication**: Use **I²C** for low-speed peripherals and **SPI** for high-speed peripherals.
3. **Vehicle-to-Cloud/External Systems**: Use **TCP/IP** for diagnostics, telemetry, and software updates.

---

##### Benefits
* The learning journey most likely will fill the knowledge goals
* The requirements will be fully  implemented

##### Drawbacks
 * complexity and fail pruner
 * tighter schedule

### Confirmation

At the end of the first product, "DES_Instrument _Cluster", the decision shall be confirmed as  VALID or INVALID
with report of of the pros and cons faced during the first product development.

**Comment by afmyhouse** [comment]
# Communication Protocols for EV: Overview and Comparison

In the context of an electric vehicle (EV), communication protocols must be chosen based on their reliability, speed, bandwidth, and specific use cases. Here's a detailed analysis:

---

## 1. TCP/IP
**Use Case**: Communication between ECUs (Electronic Control Units) and external systems (e.g., diagnostics, telematics).

### Pros
- **High Interoperability**: Standardized protocol used across devices and platforms.
- **Wide Range of Applications**: Well-suited for cloud integration, OTA updates, and diagnostics.
- **Scalability**: Can support multiple nodes and extended networks.
- **Security Features**: Encryption protocols like TLS can be layered on top for secure communication.

### Cons
- **Latency**: Higher compared to real-time protocols; unsuitable for time-critical operations like ABS.
- **Complexity**: Requires a robust stack implementation, increasing software and hardware complexity.
- **Resource-Intensive**: Demands more processing power and memory, which may not be ideal for constrained ECUs.

**Best Fit**: Vehicle-to-cloud communication, telemetry, remote diagnostics.

---

## 2. CAN (Controller Area Network)
**Use Case**: Intra-vehicle communication between ECUs (engine, battery management, etc.).

### Pros
- **Robustness**: Reliable even in noisy environments, critical for automotive applications.
- **Real-Time Capability**: Prioritized message delivery ensures low-latency communication for critical systems.
- **Low Cost**: Simple hardware implementation with wide industry adoption.
- **Fault Tolerance**: Detects errors and ensures data integrity.

### Cons
- **Limited Bandwidth**: 1 Mbps (CAN FD can extend to 5 Mbps but still limited for high-data-rate applications like video streams).
- **No Native Security**: Vulnerable to attacks without added layers of encryption or authentication.

**Best Fit**: Critical vehicle systems like engine control, battery management, and safety systems.

---

## 3. I²C (Inter-Integrated Circuit)
**Use Case**: Communication between an ECU and its peripherals (e.g., sensors, small displays).

### Pros
- **Simple Architecture**: Two-wire protocol (SDA, SCL) makes it easy to implement and cost-effective.
- **Multi-Master Support**: Multiple ECUs can communicate with the same peripheral network.
- **Low Resource Usage**: Minimal processing and memory requirements.

### Cons
- **Speed Limitation**: Maximum speed typically 400 kbps (fast mode up to 3.4 Mbps), insufficient for high-throughput applications.
- **Distance Constraint**: Effective only over short distances (a few meters).
- **Bus Contention**: All devices share the same bus, which can lead to data collisions.

**Best Fit**: Low-speed peripherals like temperature sensors, light sensors, or small LCDs.

---

## 4. SPI (Serial Peripheral Interface)
**Use Case**: High-speed communication between an ECU and its peripherals (e.g., ADCs, high-speed displays).

### Pros
- **High Speed**: Speeds up to tens of Mbps, suitable for high-data-rate peripherals.
- **Full-Duplex Communication**: Simultaneous send and receive operations.
- **Flexibility**: Works well for both short and medium distances; customizable configurations.

### Cons
- **No Standard Addressing**: Each device requires a dedicated chip select (CS) line, complicating designs with many peripherals.
- **No Error Detection**: Relies on additional software/hardware for error handling.

**Best Fit**: High-speed peripherals like high-resolution displays, real-time sensors, or ADCs.

---
